---
name: Ledger rule enforcer

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'

jobs:
  ledger_rule_enforcer:
    name: Run Ledger rule enforcer using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_guidelines_enforcer.yml@v1
    with:
      run_for_devices: '["nanos", "nanox", "nanosp", "stax", "flex"]'
